export const kratosRegistryAbi = [
  {
    type: 'constructor',
    inputs: [{ name: '_agent', type: 'address', internalType: 'address' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'agent',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'audits',
    inputs: [{ name: '', type: 'bytes32', internalType: 'bytes32' }],
    outputs: [
      { name: 'target', type: 'address', internalType: 'address' },
      { name: 'sourceHash', type: 'bytes32', internalType: 'bytes32' },
      { name: 'auditedAt', type: 'uint64', internalType: 'uint64' },
      { name: 'severity', type: 'uint8', internalType: 'uint8' },
      { name: 'findingsCount', type: 'uint16', internalType: 'uint16' },
      { name: 'attestationUID', type: 'bytes32', internalType: 'bytes32' },
      { name: 'tier', type: 'uint8', internalType: 'uint8' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getAudit',
    inputs: [
      { name: 'target', type: 'address', internalType: 'address' },
      { name: 'sourceHash', type: 'bytes32', internalType: 'bytes32' },
    ],
    outputs: [
      {
        name: '',
        type: 'tuple',
        internalType: 'struct KratosRegistry.AuditRecord',
        components: [
          { name: 'target', type: 'address', internalType: 'address' },
          { name: 'sourceHash', type: 'bytes32', internalType: 'bytes32' },
          { name: 'auditedAt', type: 'uint64', internalType: 'uint64' },
          { name: 'severity', type: 'uint8', internalType: 'uint8' },
          { name: 'findingsCount', type: 'uint16', internalType: 'uint16' },
          { name: 'attestationUID', type: 'bytes32', internalType: 'bytes32' },
          { name: 'tier', type: 'uint8', internalType: 'uint8' },
        ],
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'owner',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'recordAudit',
    inputs: [
      { name: 'target', type: 'address', internalType: 'address' },
      { name: 'sourceHash', type: 'bytes32', internalType: 'bytes32' },
      { name: 'severity', type: 'uint8', internalType: 'uint8' },
      { name: 'findingsCount', type: 'uint16', internalType: 'uint16' },
      { name: 'attestationUID', type: 'bytes32', internalType: 'bytes32' },
      { name: 'tier', type: 'uint8', internalType: 'uint8' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'renounceOwnership',
    inputs: [],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'setAgent',
    inputs: [{ name: '_newAgent', type: 'address', internalType: 'address' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'totalAudits',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'transferOwnership',
    inputs: [{ name: 'newOwner', type: 'address', internalType: 'address' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'event',
    name: 'AuditRecorded',
    inputs: [
      { name: 'auditKey', type: 'bytes32', indexed: true, internalType: 'bytes32' },
      { name: 'target', type: 'address', indexed: true, internalType: 'address' },
      { name: 'sourceHash', type: 'bytes32', indexed: true, internalType: 'bytes32' },
      { name: 'severity', type: 'uint8', indexed: false, internalType: 'uint8' },
      { name: 'findingsCount', type: 'uint16', indexed: false, internalType: 'uint16' },
      { name: 'attestationUID', type: 'bytes32', indexed: false, internalType: 'bytes32' },
      { name: 'tier', type: 'uint8', indexed: false, internalType: 'uint8' },
      { name: 'timestamp', type: 'uint64', indexed: false, internalType: 'uint64' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'OwnershipTransferred',
    inputs: [
      { name: 'previousOwner', type: 'address', indexed: true, internalType: 'address' },
      { name: 'newOwner', type: 'address', indexed: true, internalType: 'address' },
    ],
    anonymous: false,
  },
  {
    type: 'error',
    name: 'AuditAlreadyExists',
    inputs: [],
  },
  {
    type: 'error',
    name: 'NotAgent',
    inputs: [],
  },
  {
    type: 'error',
    name: 'OwnableInvalidOwner',
    inputs: [{ name: 'owner', type: 'address', internalType: 'address' }],
  },
  {
    type: 'error',
    name: 'OwnableUnauthorizedAccount',
    inputs: [{ name: 'account', type: 'address', internalType: 'address' }],
  },
  {
    type: 'error',
    name: 'ZeroSourceHash',
    inputs: [],
  },
] as const;
