[profile.default]
solc = "0.8.24"
src = "src"
out = "out"
libs = ["lib"]
test = "test"
script = "script"
optimizer = true
optimizer_runs = 1000000
via_ir = false

[rpc_endpoints]
base = "${BASE_MAINNET_RPC}"

[etherscan]
base = { key = "${BASESCAN_API_KEY}", url = "https://api.basescan.org/api" }
